Update main_1.yml

diff --git a/.github/workflows/main_1.yml b/.github/workflows/main_1.yml
--- a/.github/workflows/main_1.yml
+++ b/.github/workflows/main_1.yml
@@ -66,6 +66,9 @@ jobs:
             
             echo "▶️ Starting/Resuming yt-dlp download through WARP (Time left: $((REMAINING / 60)) minutes)..."
             
+            # Disable GitHub's strict error failing so the 124 code doesn't crash the script
+            set +e
+            
             # Apply timeout DIRECTLY to yt-dlp
             timeout --signal=SIGINT ${REMAINING}s yt-dlp \
               --cookies cookies.txt \
@@ -80,12 +83,15 @@ jobs:
               --embed-metadata \
               --remote-components ejs:github \
               --extractor-args "youtube:player_client=tv,web" \
-              -o "1_%(title)s_part_%(epoch)s.%(ext)s" \
+              -o "${STREAMER_NAME}_${FILE_PREFIX}_%(title)s_part_%(epoch)s.%(ext)s" \
               "$TARGET_URL"
             
             EXIT_CODE=$?
             
-            # timeout command automatically returns 124 when it stops a process
+            # Re-enable GitHub's strict error failing
+            set -e
+            
+            # timeout command automatically returns 124 when it successfully stops a process
             if [ $EXIT_CODE -eq 124 ]; then
               echo "🛑 340-minute limit hit! yt-dlp gracefully stopped."
               break
